In [1]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

In [2]:
d = {'sales': [100000,222000,1000000,522000,111111,222222,1111111,20000,75000,90000,1000000,10000],
'city': ['Tampa','Tampa','Orlando','Jacksonville','Miami','Jacksonville','Miami','Miami','Orlando','Orlando','Orlando','Orlando'],
'size': ['Small', 'Medium','Large','Large','Small','Medium','Large','Small','Medium','Medium','Medium','Small',]}

In [4]:
df = pd.DataFrame(data=d)

In [5]:
df.head()

     sales          city    size
0   100000         Tampa   Small
1   222000         Tampa  Medium
2  1000000       Orlando   Large
3   522000  Jacksonville   Large
4   111111         Miami   Small

In [7]:
df['size'].unique()

array(['Small', 'Medium', 'Large'], dtype=object)

In [8]:
sizes = ['Small', 'Medium', 'Large']

In [11]:
enc = OrdinalEncoder(categories=[sizes])

In [12]:
enc.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.]])

In [13]:
df['size'] = enc.fit_transform(df[['size']])

In [14]:
df.head()

     sales          city  size
0   100000         Tampa   0.0
1   222000         Tampa   1.0
2  1000000       Orlando   2.0
3   522000  Jacksonville   2.0
4   111111         Miami   0.0