In [43]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

In [44]:
dataset = pd.read_csv("500hits.csv", encoding = 'latin-1')

In [75]:
df = pd.DataFrame(dataset)

In [76]:
df.head()

,PLAYER,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA,HOF
0,Ty Cobb,24,3035,11434,2246,4189,724,295,117,726,1249,357,892,178,0.366,1
1,Stan Musial,22,3026,10972,1949,3630,725,177,475,1951,1599,696,78,31,0.331,1
2,Tris Speaker,22,2789,10195,1882,3514,792,222,117,724,1381,220,432,129,0.345,1
3,Derek Jeter,20,2747,11195,1923,3465,544,66,260,1311,1082,1840,358,97,0.310,1
4,Honus Wagner,21,2792,10430,1736,3430,640,252,101,0,963,327,722,15,0.329,1

In [46]:
df.shape

(465, 16)

In [47]:
X = df.drop(columns= ["PLAYER","HOF"])
y = df.HOF

In [48]:
X.head(6)

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA
0,24,3035,11434,2246,4189,724,295,117,726,1249,357,892,178,0.366
1,22,3026,10972,1949,3630,725,177,475,1951,1599,696,78,31,0.331
2,22,2789,10195,1882,3514,792,222,117,724,1381,220,432,129,0.345
3,20,2747,11195,1923,3465,544,66,260,1311,1082,1840,358,97,0.310
4,21,2792,10430,1736,3430,640,252,101,0,963,327,722,15,0.329
5,23,3308,11988,1816,3419,646,59,452,1844,1845,1393,168,116,0.285

In [49]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: HOF, dtype: int64

In [50]:
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=11, test_size=0.2)

In [51]:
df.head()

,PLAYER,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA,HOF
0,Ty Cobb,24,3035,11434,2246,4189,724,295,117,726,1249,357,892,178,0.366,1
1,Stan Musial,22,3026,10972,1949,3630,725,177,475,1951,1599,696,78,31,0.331,1
2,Tris Speaker,22,2789,10195,1882,3514,792,222,117,724,1381,220,432,129,0.345,1
3,Derek Jeter,20,2747,11195,1923,3465,544,66,260,1311,1082,1840,358,97,0.310,1
4,Honus Wagner,21,2792,10430,1736,3430,640,252,101,0,963,327,722,15,0.329,1

In [52]:
df.describe().round(3)

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA,HOF
count,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000
mean,17.049,2048.699,7511.456,1150.314,2170.247,380.953,78.555,201.049,894.260,783.561,847.471,195.905,58.084,0.289,0.329
std,2.765,354.392,1294.066,289.635,424.191,96.483,49.363,143.623,486.193,327.432,489.224,181.846,48.028,0.021,0.475
min,11.000,1331.000,4981.000,601.000,1660.000,177.000,3.000,9.000,0.000,239.000,0.000,7.000,0.000,0.246,0.000
25%,15.000,1802.000,6523.000,936.000,1838.000,312.000,41.000,79.000,640.000,535.000,436.000,63.000,22.000,0.273,0.000
50%,17.000,1993.000,7241.000,1104.000,2076.000,366.000,67.000,178.000,968.000,736.000,825.000,137.000,52.000,0.287,0.000
75%,19.000,2247.000,8180.000,1296.000,2375.000,436.000,107.000,292.000,1206.000,955.000,1226.000,285.000,84.000,0.300,1.000
max,26.000,3308.000,12364.000,2295.000,4189.000,792.000,309.000,755.000,2297.000,2190.000,2597.000,1406.000,335.000,0.366,2.000

# Standardization

In [58]:
X1 = X.iloc[:, 0:13]
X2 = X.iloc[:, 0:13]

In [59]:
from sklearn.preprocessing import StandardScaler

In [60]:
scaleStandard = StandardScaler()

In [61]:
X1 = scaleStandard.fit_transform(X1)

In [72]:
X1 = pd.DataFrame(X1, columns=['YRS', 'G', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'BB', 'SO', 'SB','CS'])

In [67]:
X1.head()

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS
0,2.516295,2.786078,3.034442,3.787062,4.764193,3.559333,4.389485,-0.585841,-0.346449,1.423013,-1.003628,3.832067,2.499511
1,1.792237,2.760655,2.677044,2.760530,3.444971,3.569709,1.996457,1.909487,2.175837,2.493089,-0.309948,-0.649080,-0.564531
2,1.792237,2.091184,2.075964,2.528955,3.171214,4.264876,2.909053,-0.585841,-0.350567,1.826585,-1.283965,1.299723,1.478163
3,1.068180,1.972543,2.849554,2.670665,3.055576,1.691719,-0.254611,0.410896,0.858071,0.912434,2.030966,0.892346,0.811161
4,1.430208,2.099658,2.257758,2.024329,2.972977,2.687780,3.517449,-0.697364,-1.841290,0.548609,-1.065016,2.896201,-0.898033

# Normalization

### This is used to converting overfitting data to fit in between 0 and 1

In [68]:
from sklearn.preprocessing import MinMaxScaler

In [69]:
scalerMinMax = MinMaxScaler(feature_range=(0,1))

In [71]:
X2 = scalerMinMax.fit_transform(X2)

In [73]:
X2 = pd.DataFrame(X2, columns=['YRS', 'G', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'BB', 'SO', 'SB','CS'])

In [74]:
X2.describe()

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS
count,465.000000,465.000000,465.000000,465.000000,465.000000,465.000000,465.000000,465.000000,465.000000,465.000000,465.000000,465.000000,465.000000
mean,0.403297,0.363024,0.342741,0.324270,0.201759,0.331630,0.246911,0.257439,0.389317,0.279119,0.326327,0.135029,0.173385
std,0.184346,0.179257,0.175276,0.170977,0.167731,0.156884,0.161317,0.192524,0.211665,0.167828,0.188381,0.129983,0.143366
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.266667,0.238240,0.208858,0.197757,0.070384,0.219512,0.124183,0.093834,0.278624,0.151717,0.167886,0.040029,0.065672
50%,0.400000,0.334851,0.306109,0.296930,0.164492,0.307317,0.209150,0.226542,0.421419,0.254741,0.317674,0.092924,0.155224
75%,0.533333,0.463328,0.433293,0.410272,0.282720,0.421138,0.339869,0.379357,0.525033,0.366991,0.472083,0.198713,0.250746
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000